### PR TITLE
Prevent random failure

### PR DESCRIPTION
**Pull request by EddieOne**
Happens very rarly for me. Somehow always causes an error for Olga, might be her ISP is caching the id.net sdk.

### CODE REVIEW

**Review by Codir — COMMENTED** [review]
With insertBefore generating more correctly js code (adding sdk.js before first script tag). But with appendChild more clearly sdk code

**Comment by EddieOne** [comment]
We have a strange issue with preloader getting stuck. Seems to only happen with wnet.ua network though, so it has been difficult to fix. I thought this change might fix it, no luck though.

**Comment by Codir** [comment]
I don't have same error in games. But I understand how You get this error.
If in head there a none script tag, then second param is "undefined" and we have error.
I checked. Yes .appendChild fixed this error. He can add SDK before other tags at head. But the main thing is that before the code of the game :0)

**Review by Codir — APPROVED** [review]

**Comment by EddieOne** [comment]
I missed one insert before. I fixed that now. I think this one will work. Thanks Andrii

**Pull request merged**
